spring.datasource.url=jdbc:h2:file:./data/pokemondb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.flyway.enabled=false

logging.file.name=logs/app.log
logging.level.ar.edu.utn.frc.tup.piii=DEBUG
